#!/usr/bin/env bash

if [ ! -f "$LOGISIM_PATH" ]; then
    echo "\$LOGISIM_PATH is either not set or does not exist.  Please set this environment variable."
    exit 1
fi

if [ $# -lt 2 ]; then
    echo "Not enough arguments supplied!"
    exit 1
fi

circuit="logisim/$1.circ"
program="programs/$2.raw"

if [ ! -f $circuit ]; then
    echo "${circuit} does not exist!"
    exit 1
fi

if [ ! -f $program ]; then
    echo "${program} does not exist!"
    exit 1
fi

java -jar "${LOGISIM_PATH}" "${circuit}" -tty speed -load "${program}"
